---
- name: Create a new Demo EC2 instance
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
      region: us-east-2
      instance_type: t2.micro
      ami: ami-0fc20dd1da406780b
      keypair: keyfile  # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: default  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
            For: Sunny
            Team: DevOps
      register: ec2
